### ISSUE TITLE
Need more help

### ISSUE THREAD

**Issue by robrecord** [dteare/raycast-1password-extension#1]
Hi, could you please add a little more help specifically about how to use opbookmarks in this context?

Is it not integrated with the extension?

Does it need to be running all the time? If so how do you recommend setting this up?

**Comment by mitchwinn** [comment]
@robrecord Follow the build instructions from he opbookmarks repo and then run `opbookmarks` (located in the target directory of the opbookmarks cloned repo). This will create the needed metadata automatically for you to use in Raycast.

**Comment by robrecord** [comment]
Thank you @mitchwinn 

Perhaps the repo owner @dteare might consider adding more help (such as this) to the README file.
